### PR TITLE
Fixed

### PR DESCRIPTION
**Pull request by Zack-Dx**
Fixed Nav and Homepage!

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
@Zack-Dx Show me the screenshot

**Comment by Zack-Dx** [comment]
> @Zack-Dx Show me the screenshot
Mailed it.

**Review by Susmita-Dey — APPROVED** [review]
LGTM.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by Susmita-Dey** [comment]
@Zack-Dx For now I'm merging this PR. But kindly create issues before any PRs. It looks good.

**Comment by Zack-Dx** [comment]
> @Zack-Dx For now I'm merging this PR. But kindly create issues before any PRs. It looks good.

Alright sure! have a great day ahead

**Pull request merged**
